# Generated by Django 5.0.1 on 2024-02-08 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
