# Generated by Django 5.0.1 on 2024-02-15 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_image_user_alter_image_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='message',
            field=models.TextField(default='Empty .. no text provided'),
            preserve_default=False,
        ),
    ]
