# Generated by Django 5.0.1 on 2024-02-21 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_leaf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaf',
            name='img',
            field=models.ImageField(upload_to='leaves/'),
        ),
        migrations.AlterField(
            model_name='leaf',
            name='percentage',
            field=models.CharField(max_length=4),
        ),
    ]
