# Generated by Django 5.0.1 on 2024-02-21 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_leaf_img_alter_leaf_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(upload_to='plant/'),
        ),
    ]
